name: CI

on:
  workflow_call:
    inputs:
      branch:
        description: 'Branch to test'
        required: false
        type: string

  push:
    branches-ignore:
      - master
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout pnpm repo
        run: pnpm install

      - name: lint
        run: pnpm run lint

      - name: Test
        run: pnpm run test
